site_name: LYJ çš„ç¬”è®°æœ¬
site_url: https://l6y6j6.github.io/mydocs/
repo_name: L6y6j6.github.io
repo_url: https://github.com/L6y6j6/L6y6j6.github.io
edit_uri: tree/main/docs
site_description: LYJ çš„ç¬”è®°æœ¬
copyright: Copyright &copy; 2024-2025 <a href="https://github.com/L6y6j6" target="_blank" rel="noopener">LYJ</a>
site_author: LYJ
use_directory_urls: true

theme:
  name: "material"
  language: "zh"
  icon:
    logo: material/notebook-outline
  favicon: assets/images/favicon.ico
  custom_dir: overrides
  features:
    - content.code.select
    - content.code.copy
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
  font: false
  palette:
    - scheme: default

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true

validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: ignore
    absolute_links: ignore
    unrecognized_links: ignore

extra_css:
  - https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  # - https://cdn.tonycrane.cc/utils/katex.min.css
  # - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  # - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - css/tasklist.css
  - css/custom.css
  - css/card.css
  - css/flink.css
  - css/changelog_extra.css
  # - css/heti.css

extra_javascript:
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js
  # - https://cdn.tonycrane.cc/utils/katex.min.js
  - js/katex.js
  # - js/heti.js
  # - js/scheme.js # this is in template 'base.html'

plugins:
  # - rss
  - search
  - glightbox:
      width: 80%
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md
        - writeups/AAA.md
  - changelog

# not_in_nav: todo.md

nav:
  - ğŸ  Home:
      - index.md
      - æ›´æ–°è®°å½•: changelog.md
      - å¾…åŠäº‹é¡¹: todo.md
      - å‹æƒ…é“¾æ¥: links.md
      - ç«™ç‚¹ç¤ºä¾‹: example.md
      - ä¸ªäººç®€ä»‹: about.md
  - ğŸ’» PC:
      - pc-guide/index.md
      - ç³»ç»Ÿå®‰è£…:
          - pc-guide/os-install/index.md
          - å®‰è£… Windows:
              - pc-guide/os-install/windows/index.md
              - WinPE: pc-guide/os-install/windows/winpe.md
              - Windows XP: pc-guide/os-install/windows/winxp.md
              - Windows 7: pc-guide/os-install/windows/win7.md
              - Windows 10: pc-guide/os-install/windows/win10.md
              - Windows 11: pc-guide/os-install/windows/win11.md
              - WinToGo: pc-guide/os-install/windows/wtg.md
          - å®‰è£… Linux:
              - pc-guide/os-install/linux/index.md
              - GUI å®‰è£…: pc-guide/os-install/linux/gui-install.md
              - CLI å®‰è£…:
                  - pc-guide/os-install/linux/cli-install/index.md
                  - Arch: pc-guide/os-install/linux/cli-install/arch.md
                  - Gentoo: pc-guide/os-install/linux/cli-install/gentoo.md
                  - LFS: pc-guide/os-install/linux/cli-install/lfs.md
          - å®‰è£… macOS:
              - pc-guide/os-install/macos/index.md
          - å®‰è£…é»‘è‹¹æœ:
              - pc-guide/os-install/hackintosh/index.md
              - ç¡¬ä»¶è¦æ±‚: pc-guide/os-install/hackintosh/hardware.md
              - é€‚é… EFI: pc-guide/os-install/hackintosh/efi.md
              - å®‰è£…é©±åŠ¨: pc-guide/os-install/hackintosh/driver.md
              - å®‰è£…è¯¦è§£: pc-guide/os-install/hackintosh/install.md
              - å„ç§é—®é¢˜: pc-guide/os-install/hackintosh/qa.md
          - å®‰è£… UNIX:
              - pc-guide/os-install/unix/index.md
              - å®‰è£… FreeBSD: pc-guide/os-install/unix/freebsd.md
              - å®‰è£… OpenBSD: pc-guide/os-install/unix/openbsd.md
              - å®‰è£… NetBSD: pc-guide/os-install/unix/netbsd.md
      - Windows æŒ‡å—:
          - pc-guide/windows/index.md
      - macOS æŒ‡å—:
          - pc-guide/macos/index.md
      - Linux æŒ‡å—:
          - pc-guide/linux/index.md
          - Arch Linux:
              - pc-guide/linux/arch/index.md
          - Ubuntu:
              - pc-guide/linux/ubuntu/index.md
      - ç”µè„‘å°é˜Ÿ:
          - pc-guide/pc-squad/index.md
          - ç»ªè®º: pc-guide/pc-squad/intro.md
          - ç”µè„‘çŸ¥è¯†å…¥é—¨ï¼ˆåŸç†å’Œæ„é€ ï¼‰: pc-guide/pc-squad/pcintro.md
          - æ‹†æœºå®æ“: pc-guide/pc-squad/practice.md
          - æœåŠ¡æ„è¯†: pc-guide/pc-squad/awareness.md
          - ç¡¬ä»¶è¿›é˜¶: pc-guide/pc-squad/hw-advanced.md
          - è½¯ä»¶è¿›é˜¶: pc-guide/pc-squad/sw-advanced.md
          - å¯»æ±‚å¸®åŠ©: pc-guide/pc-squad/help.md
          - ç”µè„‘å°é˜Ÿå¸¸è§é—®é¢˜ä¸€: pc-guide/pc-squad/question1.md
          - ç”µè„‘å°é˜Ÿå¸¸è§é—®é¢˜äºŒ: pc-guide/pc-squad/question2.md
      - LCPU Missing Semester:
          - pc-guide/lcpu-ms/index.md
  - ğŸŸ° Math:
      - math/index.md
      - é«˜ç­‰æ•°å­¦:
          - math/calculus/index.md
      - çº¿æ€§ä»£æ•°:
          - math/linear-algebra/index.md
      - æ¦‚ç‡è®º:
          - math/prob-theory/index.md
      - ä¿¡æ¯è®º:
          - math/info-theory/index.md
  - ğŸ–¥ï¸ CS:
      - cs/index.md
      - å¿…å­¦å·¥å…·:
          - ç¿»å¢™: cs/tools/over-gfw.md
          - Vim: cs/tools/Vim.md
          - Emacs: cs/tools/Emacs.md
          - Git: cs/tools/Git.md
          - GitHub: cs/tools/GitHub.md
          - GNU Make: cs/tools/GNU_Make.md
          - CMake: cs/tools/CMake.md
          - LaTeX: cs/tools/LaTeX.md
          - Docker: cs/tools/Docker.md
          - Package Manager: cs/tools/pm.md
          - æ—¥å¸¸å­¦ä¹ å·¥ä½œæµ: cs/tools/workflow.md
          - å®ç”¨å·¥å…·ç®±: cs/tools/tools.md
          - æ¯•ä¸šè®ºæ–‡: cs/tools/thesis.md
          - ä¿¡æ¯æ£€ç´¢: cs/tools/info-search.md
      - å¥½ä¹¦æ¨è: cs/book-rec.md
      - æ•°å­¦åŸºç¡€:
          - "MIT18.01/18.02: Calculus": cs/math-base/MITmaths.md
          - "MIT18.06: Linear Algebra": cs/math-base/MITLA.md
          - "MIT6.050J: Information theory and Entropy": cs/math-base/information.md
      - æ•°å­¦è¿›é˜¶:
          - "UCB CS70: discrete Math and probability theory": cs/math-advanced/CS70.md
          - "UCB CS126: probability theory": cs/math-advanced/CS126.md
          - "MIT 6.042J: Mathematics for Computer Science": cs/math-advanced/6.042J.md
          - "MIT18.330: Introduction to numerical analysis": cs/math-advanced/numerical.md
          - "Standford EE364A: Convex Optimization": cs/math-advanced/convex.md
          - "The Information Theory, Pattern Recognition, and Neural Networks": cs/math-advanced/The_Information_Theory_Pattern_Recognition_and_Neural_Networks.md
      - ç¼–ç¨‹å…¥é—¨:
          - "MIT-Missing-Semester": cs/programming-base/MIT-Missing-Semester.md
          - "Sysadmin DeCal": cs/programming-base/DeCal.md
          - Python è¯­è¨€:
              - "UCB CS61A: Structure and Interpretation of Computer Programs": cs/programming-base/Python/CS61A.md
              - "CS50P: CS50's Introduction to Programming with Python": cs/programming-base/Python/CS50P.md
          - C è¯­è¨€:
              - "Harvard CS50: This is CS50x": cs/programming-base/C/CS50.md
              - "Duke University: Introductory C Programming Specialization": cs/programming-base/C/Duke-Coursera-Intro-C.md
          - C++ è¯­è¨€:
              - "AmirKabir University of Technology AP1400-2: Advanced Programming": cs/programming-base/cpp/AUT1400.md
              - "Stanford CS106L: Standard C++ Programming": cs/programming-base/cpp/CS106L.md
              - "Stanford CS106B/X": cs/programming-base/cpp/CS106B_CS106X.md
          - Java è¯­è¨€:
              - "MIT 6.092: Introduction To Programming In Java": cs/programming-base/Java/MIT 6.092.md
          - Rust è¯­è¨€:
              - "Stanford CS110L: Safety in Systems Programming": cs/programming-base/Rust/CS110L.md
              - "KAIST CS431: Concurrent Programming": cs/programming-base/Rust/cs431.md
          - å‡½æ•°å¼è¯­è¨€:
              - "Cornell CS3110: OCaml Programming Correct + Efficient + Beautiful": cs/programming-base/Functional/CS3110.md
              - "Haskell MOOC": cs/programming-base/Functional/Haskell-MOOC.md
      - ç”µå­åŸºç¡€:
          - "EE16A&B: Designing Information Devices and Systems I&II": cs/ee-base/EE16.md
          - "UCB EE120 : Signal and Systems": cs/ee-base/signal.md
          - "MIT 6.007 Signals and Systems": cs/ee-base/Signals_and_Systems_AVO.md
      - æ•°æ®ç»“æ„ä¸ç®—æ³•:
          - "UCB CS61B: Data Structures and Algorithms": cs/data-struct-algo/CS61B.md
          - "Coursera: Algorithms I & II": cs/data-struct-algo/Algo.md
          - "MIT 6.006: Introduction to Algorithms": cs/data-struct-algo/6.006.md
          - "MIT 6.046: Design and Analysis of Algorithms": cs/data-struct-algo/6.046.md
          - "UCB CS170: Efficient Algorithms and Intractable Problems": cs/data-struct-algo/CS170.md
      - è½¯ä»¶å·¥ç¨‹:
          - "MIT 6.031: Software Construction": cs/sw-engineering/6031.md
          - "UCB CS169: software engineering": cs/sw-engineering/CS169.md
          - "CMU 17-803: Empirical Methods": cs/sw-engineering/17803.md
      - è®¡ç®—æœºç³»ç»ŸåŸºç¡€:
          - "CMU 15-213: CSAPP": cs/sys-basic/CSAPP.md
          - "Stanford CS110: Principles of Computer Systems": cs/sys-basic/CS110.md
      - ä½“ç³»ç»“æ„:
          - "Coursera: Nand2Tetris": cs/architecture/N2T.md
          - "UCB CS61C: Great Ideas in Computer Architecture": cs/architecture/CS61C.md
          - "ETHz: Digital Design and Computer Architecture": cs/architecture/DDCA.md
          - "ETHz: Computer Architecture": cs/architecture/CA.md
      - æ“ä½œç³»ç»Ÿ:
          - "MIT 6.S081: Operating System Engineering": cs/os/MIT6.S081.md
          - "UCB CS162: Operating System": cs/os/CS162.md
          - "NJU OS: Operating System Design and Implementation": cs/os/NJUOS.md
          - "HIT OS: Operating System": cs/os/HITOS.md
      - å¹¶è¡Œä¸åˆ†å¸ƒå¼ç³»ç»Ÿ:
          - "CMU 15-418/Stanford CS149: Parallel Computing": cs/par-dis-sys/CS149.md
          - "MIT 6.824: Distributed System": cs/par-dis-sys/MIT6.824.md
      - è®¡ç®—æœºç³»ç»Ÿå®‰å…¨:
          - "UCB CS161: Computer Security": cs/sys-safety/CS161.md
          - "MIT 6.1600: Foundations of Computer Security": cs/sys-safety/MIT6.1600.md
          - "MIT 6.858: Computer System Security": cs/sys-safety/MIT6.858.md
          - "ASU CSE365: Introduction to Cybersecurity": cs/sys-safety/CSE365.md
          - "ASU CSE466: Computer Systems Security": cs/sys-safety/CSE466.md
          - "SU SEED Labs": cs/sys-safety/SEEDLabs.md
      - è®¡ç®—æœºç½‘ç»œ:
          - "USTC Computer Networking:A Top-Down Approach": cs/computer-network/topdown_ustc.md
          - "Computer Networking: A Top-Down Approach": cs/computer-network/topdown.md
          - "Stanford CS144: Computer Network": cs/computer-network/CS144.md
      - æ•°æ®åº“ç³»ç»Ÿ:
          - "UCB CS186: Introduction to Database System": cs/db-sys/CS186.md
          - "CMU 15-445: Database Systems": cs/db-sys/15445.md
          - "Caltech CS122: Database System Implementation": cs/db-sys/CS122.md
          - "Stanford CS346: Database System Implementation": cs/db-sys/CS346.md
          - "CMU 15-799: Special Topics in Database Systems": cs/db-sys/15799.md
      - ç¼–è¯‘åŸç†:
          - "PKU ç¼–è¯‘åŸç†å®è·µ": cs/compiler/PKU-Compilers.md
          - "Stanford CS143: Compilers": cs/compiler/CS143.md
          - "NJU ç¼–è¯‘åŸç†": cs/compiler/NJU-Compilers.md
          - "KAIST CS420: Compiler Design": cs/compiler/CS420.md
      - ç¼–ç¨‹è¯­è¨€è®¾è®¡ä¸åˆ†æ:
          - "Stanford CS242: Programming Languages": cs/pl-des-ana/CS242.md
          - "NJU è½¯ä»¶åˆ†æ": cs/pl-des-ana/NJU-SoftwareAnalysis.md
          - "PKU è½¯ä»¶åˆ†æ": cs/pl-des-ana/PKU-SoftwareAnalysis.md
          - "Cambridge: Semantics of Programming Languages": cs/pl-des-ana/Cambridge-Semantics.md
      - è®¡ç®—æœºå›¾å½¢å­¦:
          - "GAMES101": cs/cg/GAMES101.md
          - "GAMES202": cs/cg/GAMES202.md
          - "GAMES103": cs/cg/GAMES103.md
          - "Stanford CS148": cs/cg/CS148.md
          - "CMU 15-462": cs/cg/15462.md
          - "USTC CG": cs/cg/USTC ComputerGraphics.md
      - Web å¼€å‘:
          - "MIT web development course": cs/web-dev/mitweb.md
          - "Stanford CS142: Web Applications": cs/web-dev/CS142.md
          - "University of Helsinki: Full Stack open 2022": cs/web-dev/fullstackopen.md
          - "CS571 Building UI (React & React Native)": cs/web-dev/CS571.md
      - æ•°æ®ç§‘å­¦:
          - "UCB Data100: Principles and Techniques of Data Science": cs/data-science/Data100.md
      - äººå·¥æ™ºèƒ½:
          - "Harvard CS50's Introduction to AI with Python": cs/ai/CS50.md
          - "UCB CS188: Introduction to Artificial Intelligence": cs/ai/CS188.md
      - æœºå™¨å­¦ä¹ :
          - "Coursera: Machine Learning": cs/ml/ML.md
          - "Stanford CS229: Machine Learning": cs/ml/CS229.md
          - "UCB CS189: Introduction to Machine Learning": cs/ml/CS189.md
      - æœºå™¨å­¦ä¹ ç³»ç»Ÿ:
          - "æ™ºèƒ½è®¡ç®—ç³»ç»Ÿ": cs/ml-sys/AICS.md
          - "CMU 10-414/714: Deep Learning Systems": cs/ml-sys/CMU10-414.md
          - "Machine Learning Compilation": cs/ml-sys/MLC.md
      - æ·±åº¦å­¦ä¹ :
          - "UMich EECS 498-007 / 598-005: Deep Learning for Computer Vision": cs/dl/EECS498-007.md
          - "Coursera: Deep Learning": cs/dl/CS230.md
          - "å›½ç«‹å°æ¹¾å¤§å­¦: æå®æ¯…æœºå™¨å­¦ä¹ ": cs/dl/LHY.md
          - "Stanford CS231n: CNN for Visual Recognition": cs/dl/CS231.md
          - "Stanford CS224n: Natural Language Processing": cs/dl/CS224n.md
          - "Stanford CS224w: Machine Learning with Graphs": cs/dl/CS224w.md
          - "UCB CS285: Deep Reinforcement Learning": cs/dl/CS285.md
      - æœºå™¨å­¦ä¹ è¿›é˜¶:
          - "è¿›é˜¶è·¯çº¿å›¾": cs/ml-advanced/roadmap.md
          - "CMU 10-708: Probabilistic Graphical Models": cs/ml-advanced/CMU10-708.md
          - "Columbia STAT 8201: Deep Generative Models": cs/ml-advanced/STAT8201.md
          - "U Toronto STA 4273 Winter 2021: Minimizing Expectations": cs/ml-advanced/STA4273.md
          - "Stanford STATS214 / CS229M: Machine Learning Theory": cs/ml-advanced/CS229M.md
  - ğŸ”¬ EE:
      - ee/index.md
  - ğŸ‡¬ğŸ‡§ English:
      - english/index.md
      - å››çº§:
          - english/cet4/index.md
      - å…­çº§:
          - english/cet6/index.md
      - é›…æ€:
          - english/ielts/index.md
      - æ‰˜ç¦:
          - english/toefl/index.md
      - GRE:
          - english/gre/index.md
  - ğŸ SS:
      - ss/index.md
      - ç»æµå­¦åŸç†:
          - ss/poe/index.md
      - æ—¥æœ¬ç»æµ:
          - ss/jp-economics/index.md
      - ç¤¾ä¼šç§‘å­¦ä¸­çš„è®¡ç®—æ€ç»´ä¸æ–¹æ³•:
          - ss/ss-cal/index.md
  - ğŸ§‘â€ğŸ¨ Art:
      - art/index.md
      - ğŸ¥ ç”µå½±:
          - art/films/index.md
          - æˆ‘çš„ Top æ¦œ: art/films/top.md
          - è®¤è¯†ç”µå½±:
              - art/films/understand/index.md
          - æˆ‘çš„å½±è¯„:
              - art/films/my-review/index.md
          - å½±è¯„æ”¶è—:
              - art/films/review-collection/index.md
      - ğŸ¿ ç”µè§†å‰§:
          - art/series/index.md
          - æˆ‘çš„ Top æ¦œ: art/series/top.md
          - æˆ‘çš„è§‚åæ„Ÿ:
              - art/series/my-review/index.md
          - è§‚åæ„Ÿæ”¶è—:
              - art/series/review-collection/index.md
      - ğŸ¨ ç»˜ç”»:
          - art/paintings/index.md
          - æœ€çˆ±çš„ç”»: art/paintings/top.md
      - ğŸµ éŸ³ä¹:
          - art/music/index.md
          - æœ€çˆ±çš„éŸ³ä¹: art/music/top.md
      - ğŸ“¹ æ‘„å½±:
          - art/photography/index.md
          - æœ€çˆ±çš„æ‘„å½±: art/photography/top.md
  - ğŸŒ¿ Life:
      - life/index.md
      - ğŸ“– è¯»ä¹¦:
          - life/reading/index.md
          - çº¢æ¥¼æ¢¦:
              - life/reading/hlm/index.md
          - ç½ªä¸ç½š:
              - life/reading/zyf/index.md
      - âœˆï¸ æ—…è¡Œ:
          - life/travel/index.md
          - éƒ‘å·: life/travel/zhengzhou.md
          - è¥¿å®‰: life/travel/xian.md
